version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - kafka
      - mongodb
    environment:
      DB_URI: mongodb://mongodb:27017/smart_hiring
      KAFKA_TOPIC: tracking-events
      KAFKA_CONNECTION_STRING: kafka:9092
      KAFKA_RETRIES: 5
      KAFKA_GROUP_ID: tracking-consumer-group
      SMART_ENVIOS_TRACK_API: http://api.carriers.com.br/client/Carriers/Tracking
      SERVER_PORT: 3000
      TOKEN: ''
    ports:
      - '3000:3000'

volumes:
  mongodb_data:
