version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-net

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tracking-events:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - kafka
      - mongodb
    environment:
      DB_URI: mongodb://mongodb:27017/smart_hiring
      KAFKA_TOPIC: tracking-events
      KAFKA_CONNECTION_STRING: kafka:9093
      KAFKA_CLIENT_ID: tracking-service
      KAFKA_RETRIES: 5
      KAFKA_GROUP_ID: tracking-consumer-group
      SMART_ENVIOS_TRACK_API: http://api.carriers.com.br/client/Carriers/Tracking
      SERVER_PORT: 3000
      TOKEN: ''
    ports:
      - '3000:3000'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mongodb_data:
