export enum TrackingStatus {
  COLLECTED = 'COLETADO',
  IN_TRANSFER_TO_HUB = 'EM TRANSFERÊNCIA PARA O HUB',
  IN_TRANSFER_TO_BASE = 'EM TRANSFERÊNCIA PARA A BASE',
  RECEIVED_AT_BASE = 'RECEBIDO NA BASE',
  OUT_FOR_DELIVERY = 'EM ROTA DE ENTREGA',
  DELIVERY_COMPLETED = 'ENTREGA REALIZADA',
}
